export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const ROLE_CHANGE = 'ROLE_CHANGE';
export const LOGIN_ID_CHANGE = 'LOGIN_ID_CHANGE';
export const PASSWORD_CHANGE = 'PASSWORD_CHANGE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';