export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const ROLE_CHANGE = 'ROLE_CHANGE';
export const LOGIN_ID_CHANGE = 'LOGIN_ID_CHANGE';
export const PASSWORD_CHANGE = 'PASSWORD_CHANGE';
export const LOGOUT_USER = 'LOGOUT_USER';